core/urls.py
from django.urls import path
from core import views as v


app_name ='core'

urlpatterns =[
    path('', v.index, name='index'),
    path('pagina/', v.DialogoUpdate.as_view(), name='pagina'),
    path('navbar/', v.navbar, name='index'),
    path('dashjato/', v.dashboard_jato, name='dash_jato'),
    path('dashfinanceiro/', v.dashboard_financeiro, name='dash_financeiro'),
]

financeiro/urls.py
from django.urls import path
from financeiro import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from rolepermissions.decorators import has_role_decorator

app_name ='financeiro'

urlpatterns =[
    path('gerencia/', v.administracao, name='gerencia'),
    path('contrato/', v.contrato_add, name='contrato_add'),
    path('itembm/', v.itembm_add, name='itembm_add'),
    path('aprovador/', v.aprovador_add, name='aprovador_add'),
    path('bmf/', manager_required(v.BmfList.as_view()), name='bmf_list'),
    path('bmf/planejador/', v.bmf_list_planejador, name='bmf_list_planejador'),
    path('dms/', manager_required(v.DmsList.as_view()), name='dms_list'),
    path('bms/', manager_required(v.BmsList.as_view()), name='bms_list'),
    path('frs/', manager_required(v.FrsList.as_view()), name='frs_list'),
    path('bmf/<int:pk>/edit/', login_required(v.BmfUpdate.as_view()), name='bmf_update'),
    path('bmf/create/', has_role_decorator('coordenador')(v.BmfCreate.as_view()), name='bmf_create'),
    path('dms/<int:pk>/edit/', manager_required(v.DMSUpdate.as_view()), name='dms_update'),
    path('dms/create/', manager_required(v.DMSCreate.as_view()), name='dms_create'),
    path('bms/<int:pk>/edit/', manager_required(v.BmsUpdate.as_view()), name='bms_update'),
    path('bms/create/', manager_required(v.BmsCreate.as_view()), name='bms_create'),
    path('frs/<int:pk>/edit/', manager_required(v.FRSUpdate.as_view()), name='frs_update'),
    path('frs/create/', manager_required(v.FRSCreate.as_view()), name='frs_create'),
    path('bmf/<slug:slug>/', v.bmf_detail, name='bmf_detail'),
    path('bmf/deleteitem/<int:pk>/<int:id>/<int:ind>/', v.delete_item, name='delete_item'),
    path('dms/<int:pk>/', v.dms_detail, name='dms_detail'),
    path('dms/deleteitem/<int:pk>/<int:id>/', v.dmsitem_delete, name='delete_itemdms'),
    path('bms/<int:pk>/', v.bms_detail, name='bms_detail'),
    path('bms/deleteitem/<int:pk>/<int:id>/', v.bmsitem_delete, name='delete_itembms'),
    path('frs/<int:pk>/', v.frs_detail, name='frs_detail'),
    path('frs/deleteitem/<int:pk>/<int:id>/', v.frsitem_delete, name='delete_itemfrs'),
    path('import/csvcontrato/', v.import_csv, name='import_csvcontrato'),
    path('import/csvbmf/', v.import_csv_bmf, name='import_csv_bmf'),
    path('import/csvdms/', v.import_csv_dms, name='import_csv_dms'),
    path('import/csvaprovador/', v.import_csv_aprovador, name='import_csv_aprovador'),
    path('import/csvsolicitante/', v.import_csv_solicitante, name='import_csv_solicitante'),
    path('itensbm/json/<str:ref>/<int:pk>/', v.json_itens, name='json_itens'),
    path('bmf/export/xlsx/', v.export_xlsx_func_bmf, name='export_xlsx_func_bmf'),
    path('bmf/json_fat_uni/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_fat_uni, name='json_fat_uni'),
    path('bmf/json_fat_sol/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_fat_sol, name='json_fat_sol'),
    path('bmf/json_fat_tipo/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_fat_tipo, name='json_fat_tipo'),
    path('bmf/json_fat_dms/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/<str:status>/', v.json_fat_dms, name='json_fat_dms'),
]

material/urls.py
from django.urls import path
from material import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required

app_name ='material'

urlpatterns =[
    path('material/', manager_required(v.MaterialList.as_view()), name='material_list'),
    path('material/<int:pk>', v.material_detail, name='material_detail'),
    path('material/add/', manager_required(v.MaterialCreate.as_view()), name='material_add'),
    path('material/<int:pk>/edit/', manager_required(v.MaterialUpdate.as_view()), name='material_edit'),
    path('tratamento/', v.tratamento_add, name='tratamento_add'),
    path('tintaf/', v.tintafundo_add, name='tintafundo_add'),
    path('tintai/', v.tintaintermediaria_add, name='tintaintermediaria_add'),
    path('tintaa/', v.tintaacabamento_add, name='tintaacabamento_add'),
    path('material/export/xlsx/', v.export_xlsx_func_material, name='export_xlsx_func_material'),
    path('material/pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('material/import_csv/', v.import_csv, name='import_csv_material'),
    path('material/jsonmaterial/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_material, name='json_material'),
    path('material/jsontratamento/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_tratamento, name='json_tratamento'),
    path('material/jsonstatus/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_status, name='json_status'),
    path('material/jsonti/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ti, name='json_ti'),
    path('material/jsonta/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ta, name='json_ta'),
    path('upload/', v.upload_arquivos, name='upload_arquivos'),
    path('processar/', v.processar_arquivos, name='processar_arquivos'),
]

projeto/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.conf.urls.static import static
from ninja import NinjaAPI

from .api import api


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('romaneio.urls')),
    path('', include('material.urls')),
    path('', include('qualidade.urls')),
    path('', include('rdo.urls')),
    path("api/v1/", api.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('usuarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT,
        )

qualidade/urls.py
from django.urls import path
from qualidade import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from django.contrib.auth.decorators import login_required
from rolepermissions.decorators import has_role_decorator


app_name ='qualidade'

urlpatterns =[
    path('qualidade/', manager_required(v.RelatoriosList.as_view()), name='relatorios_list'),
    path('qualidade/fiscal', login_required(v.RelatoriosFiscalList.as_view()), name='relatorios_list_fiscal'),
    path('qualidade/edit/<int:pk>/', v.relatorios_edit, name='relatorios_update'),
    path('qualidade/edit/etapa/<int:pk>/', manager_required(v.EtapaUpdate.as_view()), name='etapas_update'),
    path('qualidade/<int:pk>/', v.relatorios_detail, name='relatorios_detail'),
    path('qualidade/add/', v.relatorios_add, name='relatorios_add'),
    path('photo/create/<int:pk>/', v.photo_create, name='photo_create'),
    path('pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('pdfsimple/<int:pk>/', v.render_pdf_view_simple, name='render_pdf_view_simple'),
    path('photo/delete/<int:pk>', v.delete_photo, name='photo_delete'),
    path('ass/insp/<int:pk>', v.assign_insp, name='ass_insp'),
    path('ass/coord/<int:pk>', v.assign_coord, name='ass_coord'),
    path('ass/fiscal/<int:pk>', v.assign_fiscal, name='ass_fiscal'),

    path('qualidade/check/', login_required(v.Checklist_list.as_view()), name='check_list'),
    path('qualidade/check/<int:pk>/', v.checklist_detail, name='checklist_detail'),
    path('qualidade/add/check', v.checklist_add, name='checklist_add'),
    path('qualidade/edit/check2/<int:pk>', v.checklist_edit, name='checklist_edit'),
    path('qualidade/edit/<int:pk>/check', has_role_decorator('inspetor')(v.ChecklistUpdate.as_view()), name='checklist_update'),
    path('qualidade/edit/etapa/<int:pk>/check', has_role_decorator('inspetor')(v.EtapacheckUpdate.as_view()), name='etapascheck_update'),
    path('photocheck/create', v.photo_create_check, name='photo_create_check'),
    path('pdfcheck/<int:pk>/', v.render_pdf_view_check, name='render_pdf_view_check'),
    path('photocheck/delete/<int:pk>', v.delete_photo_check, name='delete_photo_check'),
    path('pdfchecksimple/<int:pk>/', v.render_pdf_view_check_simple, name='render_pdf_view_check_simple'),

    path('qualidade/edit/<int:pk>/checkenc', has_role_decorator('encarregado')(v.ChecklistUpdateEncarregado.as_view()), name='checklist_updateenc'),
    path('qualidade/edit/etapa/<int:pk>/checkenc', has_role_decorator('encarregado')(v.EtapacheckUpdateEncarregado.as_view()), name='etapascheck_updateenc'),

]

rdo/urls.py
from django.urls import path
from rdo import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from rolepermissions.decorators import has_role_decorator

app_name ='rdo'

urlpatterns =[
    #rdo's
    path('rdo/create/', has_role_decorator('rdo')(v.RdoCreate.as_view()), name='rdo_create'),
    path('rdo/<slug:slug>/', v.rdo_detail, name='rdo_detail'),
    path('rdo/', has_role_decorator('rdo')(v.RdoList.as_view()), name='rdo_list'),
    path('rdo_fiscal/', has_role_decorator('fiscal')(v.RdoListFiscal.as_view()), name='rdo_list_fiscal'),
    path('rdo/edit/<slug:slug>/', v.rdo_edit, name='rdo_edit'),
    path('itembm/', v.itembm_add, name='itembm_add'),
    path('C', v.import_csv_itembm, name='import_csv_itembm'),
    path('rdoC/', v.import_csv_rdo, name='import_csv_rdo'),
    path('rdo/deleteitem/<int:id>/<int:ind>/', v.delete_item, name='delete_item'),
    path('rdo/<int:pk>/assinatura/', has_role_decorator('fiscal')(v.AssinaturaRDOView.as_view()), name='assinatura_rdo'),
    #Bm's
    path('bm/', has_role_decorator('bms')(v.BoletimList.as_view()), name='bm_list'),
    path('bm/<int:pk>/edit/', has_role_decorator('bms')(v.BoletimUpdate.as_view()), name='bm_update'),
    path('bm/create/', has_role_decorator('bms')(v.BoletimCreate.as_view()), name='bm_create'),
    path('bm/<int:pk>/', v.boletim_detail, name='bm_detail'),
    path('bm/<int:pk>/<int:id>/', v.bm_delete, name='bm_delete'),
    #Frs's
    path('frs/', manager_required(v.FrsList.as_view()), name='frs_list'),
    path('frs/<int:pk>/edit/', manager_required(v.FRSUpdate.as_view()), name='frs_update'),
    path('frs/create/', manager_required(v.FRSCreate.as_view()), name='frs_create'),
    path('frs/<int:pk>/', v.frs_detail, name='frs_detail'),
    path('frs/deleteitem/<int:pk>/<int:id>/', v.frsitem_delete, name='delete_itemfrs'),
    #cadastros
    path('aprovadordms/', v.aprovadordms_add, name='aprovadordms_add'),
    path('aprovadorbms/', v.aprovadorbms_add, name='aprovadorbms_add'),
    path('contrato/', v.contrato_add, name='contrato_add'),
    path('projeto_cod/', v.projeto_add, name='projeto_add'),
    path('area_rdo/', v.area_add, name='area_add'),
    path('solicitante_rdo/', v.solicitante_add, name='solicitante_add'),
    #exports/imports
    path('bmf/export/xlsx/', v.export_xlsx_func_bmf, name='export_xlsx_func_bmf'),
    path('bmf/exportmov/xlsx/', v.export_movimentacao, name='export_movimentacao'),
    path('bmf/exportmovall/xlsx/', v.export_movimentacao_completa, name='export_movimentacao_completa'),
    path('pdfbms/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('rdo/deleteass/<int:pk>/<int:id>/', v.delete_assinatura, name='delete_assinatura'),
    path('export_csv/<int:pk>/', v.export_csv_view, name='export_csv'),
    #As's
    path('as/create/', has_role_decorator('as')(v.ASCreate.as_view()), name='as_create'),
    path('as/', has_role_decorator('as')(v.ASList.as_view()), name='as_list'),
    path('as/edit/<slug:slug>/', v.as_edit, name='as_edit'),
    path('as/<slug:slug>/', v.as_detail, name='as_detail'),
    path('as/deleteitem/<int:id>/<int:ind>/', v.delete_item_as, name='delete_item_as'),
############
 ]

romaneio/urls.py
from django.urls import path
from romaneio import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required

app_name ='romaneio'

urlpatterns =[
    path('romaneios/', login_required(v.RomaneioList.as_view()), name='romaneio_list'),
    path('romaneios/<int:pk>/', v.romaneio_detail, name='romaneio_detail'),
    path('romaneios/add/', v.romaneio_add, name='romaneios_add'),

    path('romaneios/<int:pk>/edit/', v.romaneio_edit, name='romaneio_edit'),
    path('romaneios/json/', v.json_fatores, name='json_fatores'),
    path('area/', v.area_add, name='area_add'),
    path('solicitante/', v.solicitante_add, name='solicitante_add'),
    path('export/xlsx/', v.export_xlsx_func, name='export_xlsx_func'),
    path('import/csv/', v.import_csv, name='import_csv'),
    path('romaneios/jsonromaneio/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_romaneios, name='json_romaneio'),
    path('romaneios/jsonarea/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_area, name='json_area'),
    path('romaneios/jsonsolicitante/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_solicitante, name='json_solicitante'),
    path('romaneios/pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('romaneios/pdftag/<int:pk>/', v.render_pdf_view_tag, name='render_pdf_view_tag'),
]

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from material.models import Material, Romaneio

from django.shortcuts import render
from django.core import serializers
from django.db.models import Sum
from .models import DialogoComportamental, DialogoForm
from django.views.generic import CreateView, UpdateView, ListView


class DialogoUpdate(CreateView):
    model = DialogoComportamental
    template_name = 'table.html'
    form_class = DialogoForm



@login_required
def navbar(request):
    return render(request, 'profile.html')

@login_required
def index(request):
    return render(request, 'index.html')

@login_required
def dashboard_jato(request):
    # mat = Material.objects.filter(~F('modified') == F('created')).order_by('-romaneio')[:10]
    romaneios = Romaneio.objects.all().order_by('-romaneio')[:5]
    begin = "2023-01-01"
    end = "2023-12-30"
    materiais = Material.objects.filter(n_romaneio__entrada__range=[begin, end]).order_by('-modified')
    tratamento = 0
    tintaf = 0
    tintai = 0
    tintaa = 0
    for material in materiais:
        if material.jato != None:
            tratamento += material.m2
    for material in materiais:
        if material.tf != None:
            tintaf += material.m2
    for material in materiais:
        if material.ti != None:
            tintai += material.m2
    for material in materiais:
        if material.ta != None:
            tintaa += material.m2
    
    if request.method == 'POST':
        begin = request.POST.get('begin')
        end = request.POST.get('end')
        tratamento = 0
        tintaf = 0
        tintai = 0
        tintaa = 0
        materiais = Material.objects.filter(n_romaneio__entrada__range=[begin, end])
        for material in materiais:
            if material.jato != None:
                tratamento += material.m2
        for material in materiais:
            if material.tf != None:
                tintaf += material.m2
        for material in materiais:
            if material.ti != None:
                tintai += material.m2
        for material in materiais:
            if material.ta != None:
                tintaa += material.m2
    
    context={'tratamento':tratamento, 'tintaf':tintaf,'tintai':tintai,'tintaa':tintaa, 'begin':begin, 
             'end':end, 'romaneios':romaneios, 'materiais':materiais}
    return render(request, 'dash_jato.html', context)


@login_required
def dashboard_financeiro(request):
    #romaneios = Romaneio.objects.all().order_by('-romaneio')[:5]
    begin = "2023-01-01"
    end = "2023-12-30"
    status_dms = "APROVADO"
    bmf = BMF.objects.filter(data_periodo__range=[begin, end]).order_by('-modified')
    pendencias = BMF.objects.filter(data_periodo__range=[begin, end],status=False).values('funcionario__username').annotate(Sum('valor'))
    fat_total = 0
    fat_pen = 0
    fat_aprov = 0
    for item in bmf:
        if item.status == True and item.valor != None:
            fat_aprov += item.valor
    for item in bmf:
        if item.status == False and item.valor != None:
            fat_pen += item.valor
    for item in bmf:
        if item.valor != None:
            fat_total += item.valor
    if request.method == 'POST':
        begin = request.POST.get('begin')
        end = request.POST.get('end')
        status_dms = request.POST.get('status_dms')
        bmf = BMF.objects.filter(data_periodo__range=[begin, end])
        pendencias = BMF.objects.filter(data_periodo__range=[begin, end],status=False).values('funcionario__username').annotate(Sum('valor'))
        fat_total = 0
        fat_pen = 0
        fat_aprov = 0
        for item in bmf:
            if item.status == True and item.valor != None:
                fat_aprov += item.valor
        for item in bmf:
            if item.status == False and item.valor != None:
                fat_pen += item.valor
        for item in bmf:
            if item.valor != None:
                fat_total += item.valor
    
    context={'fat_aprov':fat_aprov, 'fat_pen':fat_pen,'fat_total':fat_total,'begin':begin, 
             'end':end, 'pendencias':pendencias, 'status_dms':status_dms}      
    return render(request, 'dash_financeiro.html', context)

core/templates/includes/nav_financeiro.html
{% load permission_tags %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/"><img src="/media/logobrancomonsertec.png" alt="lgo" height="25px" style="padding-bottom: 6px;margin: 0px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if user|has_role:'medidor' %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'financeiro:bmf_list' %}">RDO</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'financeiro:dms_list' %}">DMS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'financeiro:bms_list' %}">BMS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'financeiro:frs_list' %}">FRS</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'financeiro:bmf_list_planejador' %}">BMF</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'romaneio:area_add' %}">Areas</a>
                    <a class="dropdown-item" href="{% url 'romaneio:solicitante_add' %}">Solicitantes</a>
                    <a class="dropdown-item" href="{% url 'financeiro:contrato_add' %}">Contrato</a>
                    <a class="dropdown-item" href="{% url 'financeiro:itembm_add' %}">Item Bm</a>
                    <a class="dropdown-item" href="{% url 'financeiro:aprovador_add' %}">Aprovador</a>
                    {% if user|has_role:'gerencia' %}
                    <a class="dropdown-item" href="{% url 'financeiro:import_csvcontrato' %}">Import itens contrato CSV(adm)</a>
                    <a class="dropdown-item" href="{% url 'financeiro:import_csv_bmf' %}">Import BMF CSV(adm)</a>
                    <a class="dropdown-item" href="{% url 'financeiro:import_csv_dms' %}">Import DMS (adm)</a>
                    <a class="dropdown-item" href="{% url 'financeiro:import_csv_aprovador' %}">Import Aprovador (adm)</a>
                    <a class="dropdown-item" href="{% url 'financeiro:import_csv_solicitante' %}">Import Solicitante (adm)</a>
                    {% endif %}
                </div>
            </li>
        </ul>
        <form action="." method="GET" class="form-inline">
            <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
            <input type="submit" class="btn btn-secondary" style="margin-left: 10px;" value="OK">
          </form>
        {% if user.is_authenticated %}
            <ul class="navbar-nav px3">
                    <li class="nav-item">
                    <a class="nav-link">Usuario: {{ user.username }} </a>
                    </li>
            </ul>
        {% endif %}
    </div>
</nav>

core/templates/includes/nav_jetflow.html
{% load permission_tags %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/"><img src="/media/logobrancomonsertec.png" alt="lgo" height="25px" style="padding-bottom: 6px;margin: 0px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'romaneio:romaneio_list' %}">Romaneios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'material:material_list' %}">Materiais</a>
            </li>
         
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'romaneio:area_add' %}">Areas</a>
                    <a class="dropdown-item" href="{% url 'romaneio:solicitante_add' %}">Solicitantes</a>
                    <a class="dropdown-item" href="{% url 'material:tratamento_add' %}">Tratamentos</a>
                    <a class="dropdown-item" href="{% url 'material:tintafundo_add' %}">Primers</a>
                    <a class="dropdown-item" href="{% url 'material:tintaintermediaria_add' %}">Tintas intermediárias</a>
                    <a class="dropdown-item" href="{% url 'material:tintaacabamento_add' %}">Tintas acabamentos</a>
                    {% if user|has_role:'gerencia' %}
                    <a class="dropdown-item" href="{% url 'romaneio:import_csv' %}">Import romaneio CSV(adm)</a>
                    <a class="dropdown-item" href="{% url 'material:import_csv_material' %}">Import material CSV(adm)</a>
                    {% endif %}
                </div>
            </li>
        </ul>
        <form action="." method="GET" class="form-inline">
            <input type="text" id="q" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="Busca">
            <input type="submit" class="btn btn-secondary" style="margin-left: 10px;" value="OK">
          </form>
        {% if user.is_authenticated %}
            <ul class="navbar-nav px3">
                    <li class="nav-item">
                    <a class="nav-link">Usuario: {{ user.username }} </a>
                    </li>
            </ul>
        {% endif %}
    </div>
</nav>

core/templates/includes/nav_qualidade.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/"><img src="/media/logobrancomonsertec.png" alt="lgo" height="25px" style="padding-bottom: 6px;margin: 0px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qualidade:relatorios_list' %}">Relatórios</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'romaneio:area_add' %}">Areas</a>
                    <a class="dropdown-item" href="{% url 'romaneio:solicitante_add' %}">Solicitantes</a>
                    <a class="dropdown-item" href="{% url 'material:tratamento_add' %}">Tratamentos</a>
                    <a class="dropdown-item" href="{% url 'material:tintafundo_add' %}">Primers</a>
                    <a class="dropdown-item" href="{% url 'material:tintaintermediaria_add' %}">Tintas intermediárias</a>
                    <a class="dropdown-item" href="{% url 'material:tintaacabamento_add' %}">Tintas acabamentos</a>
                </div>
            </li>
	    <li class="nav-item">
                <a class="nav-link" href="{% url 'qualidade:check_list' %}"">Checklist</a>
            </li>
        </ul>
        <form action="." method="GET" class="form-inline">
            <input type="text" id="q" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="Busca">
            <input type="submit" class="btn btn-secondary" style="margin-left: 10px;" value="OK">
          </form>
        {% if user.is_authenticated %}
            <ul class="navbar-nav px3">
                    <li class="nav-item">
                    <a class="nav-link">Usuario: {{ user.username }} </a>
                    </li>
            </ul>
        {% endif %}
    </div>
</nav>