core/urls.py
from django.urls import path
from core import views as v


app_name ='core'

urlpatterns =[
    path('', v.index, name='index'),
    path('pagina/', v.DialogoUpdate.as_view(), name='pagina'),
    path('navbar/', v.navbar, name='index'),
    path('dashjato/', v.dashboard_jato, name='dash_jato'),
    path('dashfinanceiro/', v.dashboard_financeiro, name='dash_financeiro'),
]

material/urls.py
from django.urls import path
from material import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required

app_name ='material'

urlpatterns =[
    path('material/', manager_required(v.MaterialList.as_view()), name='material_list'),
    path('material/<int:pk>', v.material_detail, name='material_detail'),
    path('material/add/', manager_required(v.MaterialCreate.as_view()), name='material_add'),
    path('material/<int:pk>/edit/', manager_required(v.MaterialUpdate.as_view()), name='material_edit'),
    path('tratamento/', v.tratamento_add, name='tratamento_add'),
    path('tintaf/', v.tintafundo_add, name='tintafundo_add'),
    path('tintai/', v.tintaintermediaria_add, name='tintaintermediaria_add'),
    path('tintaa/', v.tintaacabamento_add, name='tintaacabamento_add'),
    path('material/export/xlsx/', v.export_xlsx_func_material, name='export_xlsx_func_material'),
    path('material/pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('material/import_csv/', v.import_csv, name='import_csv_material'),
    path('material/jsonmaterial/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_material, name='json_material'),
    path('material/jsontratamento/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_tratamento, name='json_tratamento'),
    path('material/jsonstatus/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_status, name='json_status'),
    path('material/jsonti/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ti, name='json_ti'),
    path('material/jsonta/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ta, name='json_ta'),
    path('upload/', v.upload_arquivos, name='upload_arquivos'),
    path('processar/', v.processar_arquivos, name='processar_arquivos'),
]

projeto/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.conf.urls.static import static
from ninja import NinjaAPI

from .api import api


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('romaneio.urls')),
    path('', include('material.urls')),
    path('', include('qualidade.urls')),
    path('', include('rdo.urls')),
    path("api/v1/", api.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('usuarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT,
        )

qualidade/urls.py
from django.urls import path
from qualidade import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from django.contrib.auth.decorators import login_required
from rolepermissions.decorators import has_role_decorator


app_name ='qualidade'

urlpatterns =[
    path('qualidade/', manager_required(v.RelatoriosList.as_view()), name='relatorios_list'),
    path('qualidade/fiscal', login_required(v.RelatoriosFiscalList.as_view()), name='relatorios_list_fiscal'),
    path('qualidade/edit/<int:pk>/', v.relatorios_edit, name='relatorios_update'),
    path('qualidade/edit/etapa/<int:pk>/', manager_required(v.EtapaUpdate.as_view()), name='etapas_update'),
    path('qualidade/<int:pk>/', v.relatorios_detail, name='relatorios_detail'),
    path('qualidade/add/', v.relatorios_add, name='relatorios_add'),
    path('photo/create/<int:pk>/', v.photo_create, name='photo_create'),
    path('pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('pdfsimple/<int:pk>/', v.render_pdf_view_simple, name='render_pdf_view_simple'),
    path('photo/delete/<int:pk>', v.delete_photo, name='photo_delete'),
    path('ass/insp/<int:pk>', v.assign_insp, name='ass_insp'),
    path('ass/coord/<int:pk>', v.assign_coord, name='ass_coord'),
    path('ass/fiscal/<int:pk>', v.assign_fiscal, name='ass_fiscal'),

    path('qualidade/check/', login_required(v.Checklist_list.as_view()), name='check_list'),
    path('qualidade/check/<int:pk>/', v.checklist_detail, name='checklist_detail'),
    path('qualidade/add/check', v.checklist_add, name='checklist_add'),
    path('qualidade/edit/check2/<int:pk>', v.checklist_edit, name='checklist_edit'),
    path('qualidade/edit/<int:pk>/check', has_role_decorator('inspetor')(v.ChecklistUpdate.as_view()), name='checklist_update'),
    path('qualidade/edit/etapa/<int:pk>/check', has_role_decorator('inspetor')(v.EtapacheckUpdate.as_view()), name='etapascheck_update'),
    path('photocheck/create', v.photo_create_check, name='photo_create_check'),
    path('pdfcheck/<int:pk>/', v.render_pdf_view_check, name='render_pdf_view_check'),
    path('photocheck/delete/<int:pk>', v.delete_photo_check, name='delete_photo_check'),
    path('pdfchecksimple/<int:pk>/', v.render_pdf_view_check_simple, name='render_pdf_view_check_simple'),

    path('qualidade/edit/<int:pk>/checkenc', has_role_decorator('encarregado')(v.ChecklistUpdateEncarregado.as_view()), name='checklist_updateenc'),
    path('qualidade/edit/etapa/<int:pk>/checkenc', has_role_decorator('encarregado')(v.EtapacheckUpdateEncarregado.as_view()), name='etapascheck_updateenc'),

]

rdo/urls.py
from django.urls import path
from rdo import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from rolepermissions.decorators import has_role_decorator

app_name ='rdo'

urlpatterns =[
    #rdo's
    path('rdo/create/', has_role_decorator('rdo')(v.RdoCreate.as_view()), name='rdo_create'),
    path('rdo/<slug:slug>/', v.rdo_detail, name='rdo_detail'),
    path('rdo/', has_role_decorator('rdo')(v.RdoList.as_view()), name='rdo_list'),
    path('rdo_fiscal/', has_role_decorator('fiscal')(v.RdoListFiscal.as_view()), name='rdo_list_fiscal'),
    path('rdo/edit/<slug:slug>/', v.rdo_edit, name='rdo_edit'),
    path('itembm/', v.itembm_add, name='itembm_add'),
    path('C', v.import_csv_itembm, name='import_csv_itembm'),
    path('rdoC/', v.import_csv_rdo, name='import_csv_rdo'),
    path('rdo/deleteitem/<int:id>/<int:ind>/', v.delete_item, name='delete_item'),
    path('rdo/<int:pk>/assinatura/', has_role_decorator('fiscal')(v.AssinaturaRDOView.as_view()), name='assinatura_rdo'),
    #Bm's
    path('bm/', has_role_decorator('bms')(v.BoletimList.as_view()), name='bm_list'),
    path('bm/<int:pk>/edit/', has_role_decorator('bms')(v.BoletimUpdate.as_view()), name='bm_update'),
    path('bm/create/', has_role_decorator('bms')(v.BoletimCreate.as_view()), name='bm_create'),
    path('bm/<int:pk>/', v.boletim_detail, name='bm_detail'),
    path('bm/<int:pk>/<int:id>/', v.bm_delete, name='bm_delete'),
    #Frs's
    path('frs/', manager_required(v.FrsList.as_view()), name='frs_list'),
    path('frs/<int:pk>/edit/', manager_required(v.FRSUpdate.as_view()), name='frs_update'),
    path('frs/create/', manager_required(v.FRSCreate.as_view()), name='frs_create'),
    path('frs/<int:pk>/', v.frs_detail, name='frs_detail'),
    path('frs/deleteitem/<int:pk>/<int:id>/', v.frsitem_delete, name='delete_itemfrs'),
    #cadastros
    path('aprovadordms/', v.aprovadordms_add, name='aprovadordms_add'),
    path('aprovadorbms/', v.aprovadorbms_add, name='aprovadorbms_add'),
    path('contrato/', v.contrato_add, name='contrato_add'),
    path('projeto_cod/', v.projeto_add, name='projeto_add'),
    path('area_rdo/', v.area_add, name='area_add'),
    path('solicitante_rdo/', v.solicitante_add, name='solicitante_add'),
    #exports/imports
    path('bmf/export/xlsx/', v.export_xlsx_func_bmf, name='export_xlsx_func_bmf'),
    path('bmf/exportmov/xlsx/', v.export_movimentacao, name='export_movimentacao'),
    path('bmf/exportmovall/xlsx/', v.export_movimentacao_completa, name='export_movimentacao_completa'),
    path('pdfbms/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('rdo/deleteass/<int:pk>/<int:id>/', v.delete_assinatura, name='delete_assinatura'),
    path('export_csv/<int:pk>/', v.export_csv_view, name='export_csv'),
    #As's
    path('as/create/', has_role_decorator('as')(v.ASCreate.as_view()), name='as_create'),
    path('as/', has_role_decorator('as')(v.ASList.as_view()), name='as_list'),
    path('as/edit/<slug:slug>/', v.as_edit, name='as_edit'),
    path('as/<slug:slug>/', v.as_detail, name='as_detail'),
    path('as/deleteitem/<int:id>/<int:ind>/', v.delete_item_as, name='delete_item_as'),
############
 ]

romaneio/urls.py
from django.urls import path
from romaneio import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required

app_name ='romaneio'

urlpatterns =[
    path('romaneios/', login_required(v.RomaneioList.as_view()), name='romaneio_list'),
    path('romaneios/<int:pk>/', v.romaneio_detail, name='romaneio_detail'),
    path('romaneios/add/', v.romaneio_add, name='romaneios_add'),

    path('romaneios/<int:pk>/edit/', v.romaneio_edit, name='romaneio_edit'),
    path('romaneios/json/', v.json_fatores, name='json_fatores'),
    path('area/', v.area_add, name='area_add'),
    path('solicitante/', v.solicitante_add, name='solicitante_add'),
    path('export/xlsx/', v.export_xlsx_func, name='export_xlsx_func'),
    path('import/csv/', v.import_csv, name='import_csv'),
    path('romaneios/jsonromaneio/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_romaneios, name='json_romaneio'),
    path('romaneios/jsonarea/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_area, name='json_area'),
    path('romaneios/jsonsolicitante/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_solicitante, name='json_solicitante'),
    path('romaneios/pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('romaneios/pdftag/<int:pk>/', v.render_pdf_view_tag, name='render_pdf_view_tag'),
]

core/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )
    class Meta:
        abstract = True

class DialogoComportamental(models.Model):
    data = models.DateField('data')
    nome = models.CharField('nome', max_length=30)
    local = models.CharField('local', max_length=30)
    relato = models.CharField('relato', max_length=30)

class DialogoForm(forms.ModelForm):
    class Meta:
        model = DialogoComportamental
        fields = '__all__'

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from material.models import Material, Romaneio

from django.shortcuts import render
from django.core import serializers
from django.db.models import Sum
from .models import DialogoComportamental, DialogoForm
from django.views.generic import CreateView, UpdateView, ListView


class DialogoUpdate(CreateView):
    model = DialogoComportamental
    template_name = 'table.html'
    form_class = DialogoForm



@login_required
def navbar(request):
    return render(request, 'profile.html')

@login_required
def index(request):
    return render(request, 'index.html')

@login_required
def dashboard_jato(request):
    # mat = Material.objects.filter(~F('modified') == F('created')).order_by('-romaneio')[:10]
    romaneios = Romaneio.objects.all().order_by('-romaneio')[:5]
    begin = "2023-01-01"
    end = "2023-12-30"
    materiais = Material.objects.filter(n_romaneio__entrada__range=[begin, end]).order_by('-modified')
    tratamento = 0
    tintaf = 0
    tintai = 0
    tintaa = 0
    for material in materiais:
        if material.jato != None:
            tratamento += material.m2
    for material in materiais:
        if material.tf != None:
            tintaf += material.m2
    for material in materiais:
        if material.ti != None:
            tintai += material.m2
    for material in materiais:
        if material.ta != None:
            tintaa += material.m2
    
    if request.method == 'POST':
        begin = request.POST.get('begin')
        end = request.POST.get('end')
        tratamento = 0
        tintaf = 0
        tintai = 0
        tintaa = 0
        materiais = Material.objects.filter(n_romaneio__entrada__range=[begin, end])
        for material in materiais:
            if material.jato != None:
                tratamento += material.m2
        for material in materiais:
            if material.tf != None:
                tintaf += material.m2
        for material in materiais:
            if material.ti != None:
                tintai += material.m2
        for material in materiais:
            if material.ta != None:
                tintaa += material.m2
    
    context={'tratamento':tratamento, 'tintaf':tintaf,'tintai':tintai,'tintaa':tintaa, 'begin':begin, 
             'end':end, 'romaneios':romaneios, 'materiais':materiais}
    return render(request, 'dash_jato.html', context)


@login_required
def dashboard_financeiro(request):
    #romaneios = Romaneio.objects.all().order_by('-romaneio')[:5]
    begin = "2023-01-01"
    end = "2023-12-30"
    status_dms = "APROVADO"
    bmf = BMF.objects.filter(data_periodo__range=[begin, end]).order_by('-modified')
    pendencias = BMF.objects.filter(data_periodo__range=[begin, end],status=False).values('funcionario__username').annotate(Sum('valor'))
    fat_total = 0
    fat_pen = 0
    fat_aprov = 0
    for item in bmf:
        if item.status == True and item.valor != None:
            fat_aprov += item.valor
    for item in bmf:
        if item.status == False and item.valor != None:
            fat_pen += item.valor
    for item in bmf:
        if item.valor != None:
            fat_total += item.valor
    if request.method == 'POST':
        begin = request.POST.get('begin')
        end = request.POST.get('end')
        status_dms = request.POST.get('status_dms')
        bmf = BMF.objects.filter(data_periodo__range=[begin, end])
        pendencias = BMF.objects.filter(data_periodo__range=[begin, end],status=False).values('funcionario__username').annotate(Sum('valor'))
        fat_total = 0
        fat_pen = 0
        fat_aprov = 0
        for item in bmf:
            if item.status == True and item.valor != None:
                fat_aprov += item.valor
        for item in bmf:
            if item.status == False and item.valor != None:
                fat_pen += item.valor
        for item in bmf:
            if item.valor != None:
                fat_total += item.valor
    
    context={'fat_aprov':fat_aprov, 'fat_pen':fat_pen,'fat_total':fat_total,'begin':begin, 
             'end':end, 'pendencias':pendencias, 'status_dms':status_dms}      
    return render(request, 'dash_financeiro.html', context)

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Jet Flow</title>
    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap_modified.css' %}">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- selec2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Alpine Plugins -->
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>
    <!-- Alpine Core -->
    <script defer src="//unpkg.com/alpinejs" defer></script>
    {% block css %}   {% endblock css %} 
  </head>
  <body>
	<div class="container">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top navbar-person">
        <a class="navbar-brand" href="/"><img src="/media/logobrancomonsertec.png" alt="lgo" height="25px" style="padding-bottom: 6px;margin: 0px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
      </ul>
            {% if user.is_authenticated %}
            <form action="." method="GET" class="form-inline">
                <input type="text" id="q" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="Busca">
                <input type="submit" class="btn btn-secondary" style="margin-left: 10px;" value="OK">
              </form>
                <ul class="navbar-nav px3">
                        <li class="nav-item">
                        <a href="#"  class="nav-link">Usuario: {{ user.username }} </a>
                        </li>
                </ul>
            {% endif %}
        </div>
    </nav>
      <!--msb: main sidebar-->
            {% if user.is_authenticated %}
      <div class="msb text-light" id="msb" style="margin-top: 50px;">
              <nav class="navbar navbar-default" role="navigation">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                      <div class="brand-wrapper">
                          <!-- Brand -->
                          <div class="brand-name-wrapper">
                              <a class="navbar-brand" href="#" style="width: 100%;">
                                  Menu<i id="msbo" class="fa fa-solid fa-bars pull-right" style="margin-top: 5px;"></i>
                              </a>
                          </div>
      
                      </div>
      
                  </div>
      
                  <!-- Main Menu -->
                  <div class="side-menu-container" style="width: 100%;">
                      <ul class="nav navbar-nav">
                        <!-- Dropdown-->
                        <li  id="dropdown0">
                            <a data-toggle="collapse" href="#dropdown-lvl0">
                                <i class="fa fa-puzzle-piece"></i>Cadastros
                              <span class="caret"></span>
                          </a>
                            <!-- Dropdown level 1 -->
                            <div id="dropdown-lvl0" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'romaneio:area_add' %}"><i class="fa fa-chevron-right"></i>Área/Unidade</a></li>
                                        <li><a href="{% url 'romaneio:solicitante_add' %}"><i class="fa fa-chevron-right"></i>Solicitante</a></li>
                                        <li><a href="{% url 'material:tratamento_add' %}"><i class="fa fa-chevron-right"></i>Tratamento</a></li>
                                        <li><a href="{% url 'material:tintafundo_add' %}"><i class="fa fa-chevron-right"></i>TF</a></li>
                                        <li><a href="{% url 'material:tintaintermediaria_add' %}"><i class="fa fa-chevron-right"></i>TI</a></li>
                                        <li><a href="{% url 'material:tintaacabamento_add' %}"><i class="fa fa-chevron-right"></i>TA</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <!-- ENDropdown -->
                          <!-- Dropdown-->
                          <li  id="dropdown">
                              <a data-toggle="collapse" href="#dropdown-lvl1">
                                  <i class="fa fa-paint-brush"></i>Canteiro de Jato
                                <span class="caret"></span>
                            </a>
                              <!-- Dropdown level 1 -->
                              <div id="dropdown-lvl1" class="panel-collapse collapse">
                                  <div class="panel-body">
                                      <ul class="nav navbar-nav">
                                          <li><a href="{% url 'romaneio:romaneio_list' %}"><i class="fa fa-chevron-right"></i>Romaneios</a></li>
                                          <li><a href="{% url 'material:material_list' %}"><i class="fa fa-chevron-right"></i>Materiais</a></li>
                                          <li><a href="{% url 'qualidade:relatorios_list' %}"><i class="fa fa-chevron-right"></i>Controle de qualidade</a></li>
                                      </ul>
                                  </div>
                              </div>
                          </li>
                          <!-- ENDropdown -->
                          <!-- Dropdown2-->
                          <li  id="dropdown2">
                            <a data-toggle="collapse" href="#dropdown-lvl2">
                                <i class="fa fa-industry"></i>Produção
                              <span class="caret"></span>
                          </a>
                            <!-- Dropdown level 1 -->
                            <div id="dropdown-lvl2" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'qualidade:check_list' %}"><i class="fa fa-chevron-right"></i>Check-List</a></li>
                                        <li><a href="#"><i class="fa fa-chevron-right"></i>RDO</a></li>                        
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <!-- ENDropdown -->
                        <!-- Dropdown3-->
                        <li  id="dropdown3">
                            <a data-toggle="collapse" href="#dropdown-lvl3">
                                <i class="fa fa-money"></i>Financeiro
                              <span class="caret"></span>
                          </a>
                            <!-- Dropdown level 1 -->
                            <div id="dropdown-lvl3" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul class="nav navbar-nav">
                                        <li><a href="#"><i class="fa fa-chevron-right"></i>BMF</a></li>
                                        <li><a href="#"><i class="fa fa-chevron-right"></i>DMS</a></li>
                                        <li><a href="#"><i class="fa fa-chevron-right"></i>FRS</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <!-- ENDropdown -->
                     
                          <li><a href="{% url 'core:dash_jato' %}"><i class="fa fa-dashboard"></i>Dashboard</a></li>
                          
                          <li><a href="#"><i class="fa fa-heart"></i>Segurança</a></li>
                          <!-- Dropdown4-->
                        <li  id="dropdown4">
                            <a data-toggle="collapse" href="#dropdown-lvl4">
                                <i class="fa fa-upload"></i>Importações
                              <span class="caret"></span>
                          </a>
                            <!-- Dropdown level 1 -->
                            <div id="dropdown-lvl4" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'romaneio:import_csv' %}"><i class="fa fa-chevron-right"></i>Romaneio</a></li>
                                        <li><a href="{% url 'material:import_csv_material' %}"><i class="fa fa-chevron-right"></i>Materiais</a></li>
                                        <li><a href="/upload"><i class="fa fa-chevron-right"></i>Arquivo AFD(Ponto)</a></li>                                       
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <!-- ENDropdown -->
                        <li><a href="/auth/update/"><i class="fa fa-key"></i>Alterar senha</a></li>
                        <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Sair</a></li>
                      </ul>
                  </div><!-- /.navbar-collapse -->
              </nav>  
      </div>
      <!--main content wrapper-->
            {% endif %}
      <div class="mcw">
        
        {% block content %}   {% endblock content %}
      </div>
      
    </div>    

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
      $(document).ready(function(){
          $('#msbo').on('click', function(){
          $('body').toggleClass('msb-x');
      });
              
  
      });
      </script>
    {% block js %}   {% endblock js %}
  </body>
</html>

core/templates/index.html
{% extends "base.html" %}
{% block content %} 

<div class="row">
    <div class="col-sm-12">
    <div class="card bg-dark text-light">
      <div class="card-header">
        Bem vindo(a), {{ user.username }}
      </div>
      {% if user.is_authenticated %}
      <div class="card-body">
        <h5 class="card-title">Simple Task 1.0v</h5>
        <p class="card-text">Sistema de gestão e controle de recursos da obra</p>
      
      </div>
      {% endif %}
    </div>
    </div>


{% endblock %} 
{% block js %} 
<script>
    $(document).ready(function(){
        $('body').addClass('fundo')
    });
    </script>
{% endblock js %}