projeto/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.conf.urls.static import static
from ninja import NinjaAPI

from .api import api


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('romaneio.urls')),
    path('', include('material.urls')),
    path('', include('qualidade.urls')),
    path('', include('rdo.urls')),
    path("api/v1/", api.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('usuarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT,
        )

qualidade/urls.py
from django.urls import path
from qualidade import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from django.contrib.auth.decorators import login_required
from rolepermissions.decorators import has_role_decorator


app_name ='qualidade'

urlpatterns =[
    path('qualidade/', manager_required(v.RelatoriosList.as_view()), name='relatorios_list'),
    path('qualidade/fiscal', login_required(v.RelatoriosFiscalList.as_view()), name='relatorios_list_fiscal'),
    path('qualidade/edit/<int:pk>/', v.relatorios_edit, name='relatorios_update'),
    path('qualidade/edit/etapa/<int:pk>/', manager_required(v.EtapaUpdate.as_view()), name='etapas_update'),
    path('qualidade/<int:pk>/', v.relatorios_detail, name='relatorios_detail'),
    path('qualidade/add/', v.relatorios_add, name='relatorios_add'),
    path('photo/create/<int:pk>/', v.photo_create, name='photo_create'),
    path('pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('pdfsimple/<int:pk>/', v.render_pdf_view_simple, name='render_pdf_view_simple'),
    path('photo/delete/<int:pk>', v.delete_photo, name='photo_delete'),
    path('ass/insp/<int:pk>', v.assign_insp, name='ass_insp'),
    path('ass/coord/<int:pk>', v.assign_coord, name='ass_coord'),
    path('ass/fiscal/<int:pk>', v.assign_fiscal, name='ass_fiscal'),

    path('qualidade/check/', login_required(v.Checklist_list.as_view()), name='check_list'),
    path('qualidade/check/<int:pk>/', v.checklist_detail, name='checklist_detail'),
    path('qualidade/add/check', v.checklist_add, name='checklist_add'),
    path('qualidade/edit/check2/<int:pk>', v.checklist_edit, name='checklist_edit'),
    path('qualidade/edit/<int:pk>/check', has_role_decorator('inspetor')(v.ChecklistUpdate.as_view()), name='checklist_update'),
    path('qualidade/edit/etapa/<int:pk>/check', has_role_decorator('inspetor')(v.EtapacheckUpdate.as_view()), name='etapascheck_update'),
    path('photocheck/create', v.photo_create_check, name='photo_create_check'),
    path('pdfcheck/<int:pk>/', v.render_pdf_view_check, name='render_pdf_view_check'),
    path('photocheck/delete/<int:pk>', v.delete_photo_check, name='delete_photo_check'),
    path('pdfchecksimple/<int:pk>/', v.render_pdf_view_check_simple, name='render_pdf_view_check_simple'),

    path('qualidade/edit/<int:pk>/checkenc', has_role_decorator('encarregado')(v.ChecklistUpdateEncarregado.as_view()), name='checklist_updateenc'),
    path('qualidade/edit/etapa/<int:pk>/checkenc', has_role_decorator('encarregado')(v.EtapacheckUpdateEncarregado.as_view()), name='etapascheck_updateenc'),

]

rdo/urls.py
from django.urls import path
from rdo import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from rolepermissions.decorators import has_role_decorator

app_name ='rdo'

urlpatterns =[
    #rdo's
    path('rdo/create/', has_role_decorator('rdo')(v.RdoCreate.as_view()), name='rdo_create'),
    path('rdo/<slug:slug>/', v.rdo_detail, name='rdo_detail'),
    path('rdo/', has_role_decorator('rdo')(v.RdoList.as_view()), name='rdo_list'),
    path('rdo_fiscal/', has_role_decorator('fiscal')(v.RdoListFiscal.as_view()), name='rdo_list_fiscal'),
    path('rdo/edit/<slug:slug>/', v.rdo_edit, name='rdo_edit'),
    path('itembm/', v.itembm_add, name='itembm_add'),
    path('C', v.import_csv_itembm, name='import_csv_itembm'),
    path('rdoC/', v.import_csv_rdo, name='import_csv_rdo'),
    path('rdo/deleteitem/<int:id>/<int:ind>/', v.delete_item, name='delete_item'),
    path('rdo/<int:pk>/assinatura/', has_role_decorator('fiscal')(v.AssinaturaRDOView.as_view()), name='assinatura_rdo'),
    #Bm's
    path('bm/', has_role_decorator('bms')(v.BoletimList.as_view()), name='bm_list'),
    path('bm/<int:pk>/edit/', has_role_decorator('bms')(v.BoletimUpdate.as_view()), name='bm_update'),
    path('bm/create/', has_role_decorator('bms')(v.BoletimCreate.as_view()), name='bm_create'),
    path('bm/<int:pk>/', v.boletim_detail, name='bm_detail'),
    path('bm/<int:pk>/<int:id>/', v.bm_delete, name='bm_delete'),
    #Frs's
    path('frs/', manager_required(v.FrsList.as_view()), name='frs_list'),
    path('frs/<int:pk>/edit/', manager_required(v.FRSUpdate.as_view()), name='frs_update'),
    path('frs/create/', manager_required(v.FRSCreate.as_view()), name='frs_create'),
    path('frs/<int:pk>/', v.frs_detail, name='frs_detail'),
    path('frs/deleteitem/<int:pk>/<int:id>/', v.frsitem_delete, name='delete_itemfrs'),
    #cadastros
    path('aprovadordms/', v.aprovadordms_add, name='aprovadordms_add'),
    path('aprovadorbms/', v.aprovadorbms_add, name='aprovadorbms_add'),
    path('contrato/', v.contrato_add, name='contrato_add'),
    path('projeto_cod/', v.projeto_add, name='projeto_add'),
    path('area_rdo/', v.area_add, name='area_add'),
    path('solicitante_rdo/', v.solicitante_add, name='solicitante_add'),
    #exports/imports
    path('bmf/export/xlsx/', v.export_xlsx_func_bmf, name='export_xlsx_func_bmf'),
    path('bmf/exportmov/xlsx/', v.export_movimentacao, name='export_movimentacao'),
    path('bmf/exportmovall/xlsx/', v.export_movimentacao_completa, name='export_movimentacao_completa'),
    path('pdfbms/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('rdo/deleteass/<int:pk>/<int:id>/', v.delete_assinatura, name='delete_assinatura'),
    path('export_csv/<int:pk>/', v.export_csv_view, name='export_csv'),
    #As's
    path('as/create/', has_role_decorator('as')(v.ASCreate.as_view()), name='as_create'),
    path('as/', has_role_decorator('as')(v.ASList.as_view()), name='as_list'),
    path('as/edit/<slug:slug>/', v.as_edit, name='as_edit'),
    path('as/<slug:slug>/', v.as_detail, name='as_detail'),
    path('as/deleteitem/<int:id>/<int:ind>/', v.delete_item_as, name='delete_item_as'),
############
 ]

qualidade/models.py
import os
from django.db import models
from romaneio.models import Solicitante, Area
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from core.models import TimeStampedModel


CORROS = (
    ('N/A','N/A'),
    ('C1','C1'),
    ('C2','C2'),
    ('C3','C3'),
    ('C4','C4'),
    ('C5','C5'),
    ('C6','C6'),

)
    
class RelatorioInspecao(TimeStampedModel):
    funcionario = models.ForeignKey(User,on_delete=models.CASCADE)
    rip = models.AutoField(auto_created=True,unique=True,primary_key=True)
    cliente = models.CharField('Cliente',max_length=15, blank=True, null=True)
    data = models.DateField(verbose_name='Data serviço')
    rec = models.CharField(max_length=15, blank=True, null=True)
    nota = models.CharField('Nota',max_length=15, blank=True, null=True)
    tag = models.CharField('Tag',max_length=20, blank=True, null=True)
    tipo_serv = models.CharField('Tipo serviço',max_length=20, blank=True, null=True)
    unidade = models.ForeignKey(Area, on_delete=models.CASCADE, related_name='areaa')
    setor = models.CharField('Setor',max_length=15, blank=True, null=True)
    corrosividade = models.CharField(max_length=15, choices=CORROS)
    esquema_pint = models.CharField('Esquema',max_length=50, blank=True, null=True)
    esp_esquema = models.CharField("Espessura",max_length=20, blank=True, null=True)
    cor_final = models.CharField(max_length=20, blank=True, null=True)
    fiscal = models.ForeignKey(Solicitante, on_delete=models.CASCADE, related_name='solicitantee')
    inspetor = models.CharField(max_length=20, blank=True, null=True)
    rnc_n = models.BooleanField('RNC?',default=False)
    obs_inst = models.TextField('Instrumentos de medição',blank=True, null=True)
    obs_final = models.TextField('Observações finais', blank=True, null=True)
    aprovado = models.BooleanField(default=True)

    tratamento = models.CharField('Tratamento',max_length=20, blank=True, null=True)
    inicio = models.DateTimeField(verbose_name='Inicio')
    termino = models.DateTimeField(verbose_name='Fim')
    temp_ambiente = models.DecimalField('Temperatura ambiente', max_digits=4, decimal_places=1,blank=True, null=True)
    ura = models.DecimalField('Úmidade relativa', max_digits=4, decimal_places=1,blank=True, null=True)
    po = models.DecimalField('Ponto de Orvalho', max_digits=4, decimal_places=1,blank=True, null=True)
    temp_super = models.DecimalField('Temperatura da superfície', max_digits=4, decimal_places=1,blank=True, null=True)
    intemperismo = models.CharField('Grau de intemperismo',max_length=2, blank=True, null=True)
    descontaminacao = models.CharField('Descontaminação',max_length=20, blank=True, null=True)
    poeira_tam = models.CharField('Teste de poeira tamanho',max_length=10, blank=True, null=True)
    poeira_quant = models.CharField('Teste de poeira quantidade',max_length=10, blank=True, null=True)
    teor_sais = models.CharField('Teor sais soluveis na superfície',max_length=10, blank=True, null=True)
    ambiente_pintura = models.CharField('Ambiente pintura',max_length=30, blank=True, null=True)
    rugosidade = models.DecimalField('Rugosidade', max_digits=6, decimal_places=2,blank=True, null=True)
    laudo = models.BooleanField(default=True)


    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'J{}/{}'.format(str(self.rip).zfill(4),self.data.strftime('%Y'))
    def get_data(self):
        return self.data.strftime('%d/%m/%Y')
    def get_inicio(self):
        return self.inicio.strftime('%d/%m/%Y')
    def get_termino(self):
        return self.termino.strftime('%d/%m/%Y')
    def get_absolute_url(self):
        return reverse_lazy('qualidade:relatorios_detail', kwargs={'pk': self.pk})

class EtapaPintura(models.Model):
    rip_n = models.ForeignKey(RelatorioInspecao, on_delete=models.CASCADE, related_name='relatorios')
    tinta = models.CharField(max_length=20, blank=True, null=True)
    lote_a = models.CharField(max_length=20, blank=True, null=True)
    val_a = models.DateField(verbose_name='Validade lote A')
    lote_b = models.CharField(max_length=20, blank=True, null=True)
    val_b = models.DateField(verbose_name='Validade lote B', blank=True, null=True)
    lote_c = models.CharField(max_length=20, blank=True, null=True)
    val_c = models.DateField(verbose_name='Validade lote C', blank=True, null=True)
    cor_munsell = models.CharField(max_length=20, blank=True, null=True)
    temp_amb = models.IntegerField('Temp. ambiente', blank=True, null=True)
    ura = models.DecimalField('Úmidade relativa', max_digits=4, decimal_places=1,blank=True, null=True)
    po = models.DecimalField('Ponto de Orvalho', max_digits=4, decimal_places=1,blank=True, null=True)
    temp_substrato = models.DecimalField('Temperatura da substrato', max_digits=4, decimal_places=1,blank=True, null=True)
    diluente = models.CharField(max_length=15, blank=True, null=True)
    met_aplic = models.CharField(max_length=20, blank=True, null=True)
    inicio = models.DateTimeField(verbose_name='Inicio')
    termino = models.DateTimeField(verbose_name='Fim')
    inter_repintura = models.CharField(max_length=15, blank=True, null=True)
    epe = models.IntegerField('Espessura especificada', blank=True, null=True)
    eps = models.IntegerField('Espessura seca', blank=True, null=True)
    insp_visual = models.BooleanField(default=True)
    aderencia = models.CharField(max_length=15, blank=True, null=True)
    holiday = models.CharField(max_length=15, blank=True, null=True)
    laudo = models.BooleanField(default=True)
    data_insp = models.DateField(verbose_name='Data inspeção')

    class Meta:
        ordering = ('pk',)
    def __str__(self):
        return str(self.tinta)
    def get_data_insp(self):
        return self.data_insp.strftime('%d/%m/%Y')
    def get_inicio(self):
        return self.inicio.strftime('%d/%m/%Y')
    def get_termino(self):
        return self.termino.strftime('%d/%m/%Y')
    def get_val_a(self):
        return self.val_a.strftime('%d/%m/%Y')
    def get_val_b(self):
        return self.val_b.strftime('%d/%m/%Y')
    def get_val_c(self):
        return self.val_c.strftime('%d/%m/%Y')
    def get_absolute_url(self):
        return reverse_lazy('qualidade:relatorios_detail', kwargs={'pk': self.rip_n.rip })

class Photo(models.Model):
    rip_numero = models.ForeignKey(RelatorioInspecao, on_delete=models.CASCADE, verbose_name='RIP',related_name='relatorio')
    photo = models.ImageField('foto',upload_to='photos/')
    class Meta:
        ordering =('pk',)
        verbose_name = 'foto'
        verbose_name_plural = 'fotos'
    def __str__(self):
        return str(self.rip_numero)
    def delete(self, using=None, keep_parents=False):
        os.remove(self.photo.path)
        return super().delete(using, keep_parents)

class Assinatura(models.Model):
    rip_numero = models.ForeignKey(RelatorioInspecao, on_delete=models.CASCADE, verbose_name='rip',related_name='rel_ass')
    ass_insp = models.CharField(max_length=70, blank=True, null=True)
    ass_coord =  models.CharField(max_length=70, blank=True, null=True)
    ass_fiscal = models.CharField(max_length=70, blank=True, null=True)


############### CHECKLIST ################
CHOICE = (
    ('N/A','N/A'),
    ('SIM','SIM'),
    ('NÃO','NÃO'),
)
TIPOS = (
    ('PARADA','PARADA'),
    ('PROJETO','PROJETO'),
    ('NOTA','NOTA'),
    ('PLANO DE PINTURA','PLANO DE PINTURA'),
    ('INTEGRIDADE','INTEGRIDADE'),
    ('MANUTENCAO','MANUTENÇÃO'),
)

class ChecklistInspecao(TimeStampedModel):
    funcionario = models.ForeignKey(User,on_delete=models.CASCADE)
    rip = models.AutoField(auto_created=True,unique=True,primary_key=True)
    cliente = models.CharField('Cliente',max_length=15, blank=True, null=True)
    data = models.DateField(verbose_name='Data serviço')
    rec = models.CharField(max_length=15, blank=True, null=True)
    nota = models.CharField('Nota',max_length=15, blank=True, null=True)
    tag = models.CharField('Tag',max_length=20, blank=True, null=True)
    tipo_serv = models.CharField('Tipo serviço',max_length=20, choices=TIPOS)
    unidade = models.CharField('Area',max_length=30, blank=True, null=True)
    setor = models.CharField('Setor',max_length=15, blank=True, null=True)
    corrosividade = models.CharField(max_length=15, choices=CORROS)
    fiscal = models.CharField('Fiscal',max_length=30, blank=True, null=True)
    
    inspetor = models.CharField(max_length=20, blank=True, null=True)

    tratamento = models.CharField('Tratamento',max_length=50, blank=True, null=True)
    tipo_subs = models.CharField('Tipo do substrato',max_length=50, blank=True, null=True)

    
    inicio = models.DateTimeField(verbose_name='Inicio')
    termino = models.DateTimeField(verbose_name='Fim')
    temp_ambiente = models.DecimalField('Temperatura ambiente', max_digits=4, decimal_places=1, blank=True, null=True)
    ura = models.DecimalField('Úmidade relativa', max_digits=4, decimal_places=1, blank=True, null=True)
    po = models.DecimalField('Ponto de Orvalho', max_digits=4, decimal_places=1, blank=True, null=True)
    temp_super = models.DecimalField('Temperatura da superfície', max_digits=4, decimal_places=1, blank=True, null=True)
    intemperismo = models.CharField('Grau de intemperismo',max_length=2, blank=True, null=True)
    descontaminacao = models.CharField('Descontaminação',max_length=20, blank=True, null=True)
    poeira_tam = models.CharField('Teste de poeira tamanho',max_length=10, blank=True, null=True)
    poeira_quant = models.CharField('Teste de poeira quantidade',max_length=10, blank=True, null=True)
    teor_sais = models.CharField('Teor sais soluveis na superfície',max_length=10, blank=True, null=True)
    ambiente_pintura = models.CharField('Ambiente pintura',max_length=30, blank=True, null=True)
    rugosidade = models.DecimalField('Rugosidade', max_digits=6, decimal_places=2, blank=True, null=True)  

qualidade/templates/checklist_detail copy.html
{% extends "base.html" %}

{% block content %} 


    <h2>Checklist Nº {{ object }}
        <span class="pull-right">
            <a href="{% url 'qualidade:render_pdf_view_check_simple' object.pk %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-pencil"></span> gerar PDF simplificado
                </button>
            </a>

        </span>
        <span class="pull-right">
            <a href="{% url 'qualidade:render_pdf_view_check' object.pk %}">
                <button type="button" class="btn btn-success">
                    <span class="fa fa-pencil"></span> gerar PDF
                </button>
            </a>

        </span>
        <span class="pull-right">
            <a href="{% url 'qualidade:checklist_update' object.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="fa fa-pencil"></span> Editar
                </button>
            </a>

        </span>
    </h2>
    <div class="row">
    <div class="col-sm-4">
        <table class="table table-user-information table-sm">
            <tbody>
                <tr>
                    <th class="text-right">Cliente</th>
                    <td> {{ object.cliente }}</td>
                </tr>
                <tr>
                    <th class="text-right">Data</th>
                    <td>{{ object.get_data }}</td>
                </tr>
                <tr>
                    <th class="text-right">Dcoumento ref.</th>
                    <td>{{ object.rec }}</td>
                </tr>
                <tr>
                    <th class="text-right">Nota</th>
                    <td>{{ object.nota }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tipo de serviço</th>
                    <td>{{ object.tipo_serv }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-sm-4">
        <table class="table table-user-information table-sm">
            <tbody>
                <tr>
                    <th class="text-right">Unidade/Planta</th>
                    <td> {{ object.unidade }}</td>
                </tr>
                <tr>
                    <th class="text-right">Setor</th>
                    <td>{{ object.setor }}</td>
                </tr>
                <tr>
                    <th class="text-right">Corrosividade</th>
                    <td>{{ object.corrosividade }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tag</th>
                    <td>{{ object.tag }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tipo substrato</th>
                    <td>{{ object.tipo_subs }}</td>
                </tr>
                
            </tbody>
        </table>
    </div>
    <div class="col-sm-4">
        <table class="table table-user-information table-sm">
                <tr>
                    <th class="text-right">Solicitante</th>
                    <td>{{ object.fiscal }}</td>
                </tr>
                <tr>
                    <th class="text-right">Encarregado</th>
                    <td>{{ object.funcionario }}</td>
                </tr>
                <tr>
                    <th class="text-right">NC? </th>
                    <td>{% if object.rnc_n %}
                        <i class="fa fa-check-circle ok"></i>
                      {% else %}
                        <i class="fa fa-minus-circle no"></i>
                      {% endif %}</td>
                    
                </tr>
                <tr>
                    <th class="text-right">Aprovado?</th>
                    <td>{% if object.aprovado %}
                        <i class="fa fa-check-circle ok"></i>
                      {% else %}
                        <i class="fa fa-minus-circle no"></i>
                      {% endif %}</td>
                </tr>
                
            </tbody>
        </table>
    </div>
    <div class="col-sm-12">
        <table class="table table-user-information table-sm">
                <tr>
                    <th class="text-left">Todos pontos de contato foram instalados calha tipo Utec?</th>
                    <td>{{ object.calha_utec }}</td>
                </tr>
                <tr>
                    <th class="text-left">Foram pintados os guias e os pontos de contatos da tubulação?</th>
                    <td>{{ object.guia_pc }}</td>
                </tr>
                <tr>
                    <th class="text-left">Aplicado fita de proteção nos pontos com grampos de fixação?</th>
                    <td>{{ object.fita_protec }}</td>
                </tr>
                <tr>
                    <th class="text-left">Foi pintado todos trechos recomendados da REC?</th>
                    <td>{{ object.trecho_rec }}</td>
                </tr>
                <tr>
                    <th class="text-left">Foi Aplicado elastômero nos acessórios?</th>
                    <td>{{ object.elastomero }}</td>
                </tr>
                <tr>
                    <th class="text-left">Foram pintados todos os volantes e caps?</th>
                    <td>{{ object.volante_caps }}</td>
                </tr>
               
                
            </tbody>
        </table>
    </div>
    </div>
    <legend style="border-bottom: 1px solid #e5e5e5;">Tratamento da Superfície - {{ object.tratamento }} </legend>
    <table class="table table-bordered table-sm">
        <thead>
            <tr>
                <th>Inicio</th>
                <th>Termino</th>
                <th>Temp. amb.</th>
                <th>U.R.A</th>
                <th>P.O</th>
                <th>Temp. Superfície</th>
                <th>Rugosidade</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ object.get_inicio }}</td>
                <td>{{ object.get_termino }}</td>
                <td>{{ object.temp_ambiente }}</td>
                <td>{{ object.ura}}</td>
                <td>{{ object.po }}</td>
                <td>{{ object.temp_super }}</td>
                <td>{{ object.rugosidade}}</td>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered table-sm">
        <thead>
            <tr>
                
                <th>Poeira Tam</th>
                <th>Poeira QTD</th>
                <th>Teor Sais</th>
                <th>Amb pintura</th>
                <th>Intemperismo</th>
                <th>Descontaminacao</th>
                <th>Laudo</th>
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ object.poeira_tam }}</td>
                <td>{{ object.tpoeira_quant }}</td>
                <td>{{ object.teor_sais}}</td>
                <td>{{ object.ambiente_pintura }}</td>
                <td>{{ object.intemperismo }}</td>
                <td>{{ object.descontaminacao }}</td>
                <td>{% if object.laudo %}
                    <i class="fa fa-check-circle ok"></i>
                  {% else %}
                    <i class="fa fa-minus-circle no"></i>
                  {% endif %}</td>
                
            </tr>
        </tbody>
    </table>

    <legend style="border-bottom: 1px solid #e5e5e5;">Etapas de Pintura</legend>

        <div class="row">
                <div class="col-sm-6">
                    <table class="table table-user-information">
                        <tbody>
                <tr>
                    <th class="text-right">Observações instrumentos</th>
                    <td>{{ object.obs_inst }}</td>

                </tr>
            </tbody>
            </table>
            </div>
            <div class="col-sm-6">
                <table class="table table-user-information" >
                    <tbody>
            <tr>
                <th class="text-right">Observações finais</th>

                <td>{{ object.obs_final }}</td>
            </tr>
            </tbody>
            </table>
            </div>
            </div>
            <div>
                <legend style="border-bottom: 1px solid #e5e5e5;">Registro fotográfico</legend>  
                <a class="btn btn-info btn-sm" href="{% url 'qualidade:photo_create_check' %}"style="margin: 6px;">Adicionar Imagem</a>
                <div class="row" style="margin-bottom: 10px;">
                {% for item in object.checklists.all %}
                {% if item.photo %}
                <div style="flex-direction: column;display: flex; align-items: center;">
                <img src="{{ item.photo.url }}" alt="" class="img-thumbnail" width="150px">
                <a href="{% url 'qualidade:delete_photo_check' item.pk %}" class="btn btn-danger btn-sm" style="width: 50%;">delete</a>
                </div>
                {% endif %}
                {% endfor %}
                </div>
            </div>
             
            
{% endblock content %} 

{% block js %}
{% endblock js %}

qualidade/templates/photo_form.html
{% extends "base.html" %}

{% block content %} 

<h1>Adicionar Imagens</h1>
<div class="cols-6">
  <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
    <div class="col-sm-6">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </form>
 
</div>

<input hidden id="hashid" name="hashid" value="{{ pk }}" type="number">
{% endblock content %} 

{% block js %}
<script>
  $(document).ready(function(){
      $('#id_rip-_numero').attr('hidden','true');
      pk = $("#hashid").val();
      $("#id_rip_numero").val(pk);
  });
  
</script>
{% endblock js %}

qualidade/templates/relatorios_list.html
{% extends "base.html" %}


{% block content %} 
    <div class="page-header">
        <h2><i class="fa fa-user"></i> Relatorios
            <span class="pull-right">
                <div style="display: flex;">
                <a href="{% url 'qualidade:relatorios_add' %}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span>Adicionar
                    </button>                    
                </a>
                </div>
            </span>
        </h2>

        {% if objects_list %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nº Rip</th>
                    <th>Cliente</th>
                    <th>Rec/PJ/OM</th>
                    <th>Unidade/Planta</th>
                    <th class="text-center">Fiscal</th>
                    <th>Plot</th>
                </tr>
            </thead>
            <tbody>
                {% for object in objects_list %}
                <tr>
                    <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
                    <td>{{ object.cliente }}</td>
                    <td>{{ object.rec }}</td>
                    <td>{{ object.unidade }}</td>
                    <td class="text-center">{{ object.fiscal }}</td>
               	    <td><a href="{% url 'qualidade:render_pdf_view' object.pk %}"><i class="fa fa-thin fa-print"></i></a></td>
                </tr>
                 
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="alert alert-warning">Sem Itens na Lista </p>
        {% endif %}
    </div>

    {% include "includes/pagination.html" %}

{% endblock content %} 

qualidade/templates/teste.html
{% extends "base.html" %}

{% block content %} 
{% include "includes/nav_jetflow.html" %} 
<h1> funciona  {{ object }} </h1>

{% endblock content %} 