material/urls.py
from django.urls import path
from material import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required

app_name ='material'

urlpatterns =[
    path('material/', manager_required(v.MaterialList.as_view()), name='material_list'),
    path('material/<int:pk>', v.material_detail, name='material_detail'),
    path('material/add/', manager_required(v.MaterialCreate.as_view()), name='material_add'),
    path('material/<int:pk>/edit/', manager_required(v.MaterialUpdate.as_view()), name='material_edit'),
    path('tratamento/', v.tratamento_add, name='tratamento_add'),
    path('tintaf/', v.tintafundo_add, name='tintafundo_add'),
    path('tintai/', v.tintaintermediaria_add, name='tintaintermediaria_add'),
    path('tintaa/', v.tintaacabamento_add, name='tintaacabamento_add'),
    path('material/export/xlsx/', v.export_xlsx_func_material, name='export_xlsx_func_material'),
    path('material/pdf/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('material/import_csv/', v.import_csv, name='import_csv_material'),
    path('material/jsonmaterial/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_material, name='json_material'),
    path('material/jsontratamento/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_tratamento, name='json_tratamento'),
    path('material/jsonstatus/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77/<str:begin>/<str:end>/', v.json_status, name='json_status'),
    path('material/jsonti/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ti, name='json_ti'),
    path('material/jsonta/2b76e8ce5dfae938c4974bc08d48ed4e97e49d77', v.json_ta, name='json_ta'),
    path('upload/', v.upload_arquivos, name='upload_arquivos'),
    path('processar/', v.processar_arquivos, name='processar_arquivos'),
]

projeto/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.conf.urls.static import static
from ninja import NinjaAPI

from .api import api


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('romaneio.urls')),
    path('', include('material.urls')),
    path('', include('qualidade.urls')),
    path('', include('rdo.urls')),
    path("api/v1/", api.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('usuarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT,
        )

rdo/urls.py
from django.urls import path
from rdo import views as v
from django.contrib.auth.decorators import login_required
from usuarios.decorators import manager_required
from rolepermissions.decorators import has_role_decorator

app_name ='rdo'

urlpatterns =[
    #rdo's
    path('rdo/create/', has_role_decorator('rdo')(v.RdoCreate.as_view()), name='rdo_create'),
    path('rdo/<slug:slug>/', v.rdo_detail, name='rdo_detail'),
    path('rdo/', has_role_decorator('rdo')(v.RdoList.as_view()), name='rdo_list'),
    path('rdo_fiscal/', has_role_decorator('fiscal')(v.RdoListFiscal.as_view()), name='rdo_list_fiscal'),
    path('rdo/edit/<slug:slug>/', v.rdo_edit, name='rdo_edit'),
    path('itembm/', v.itembm_add, name='itembm_add'),
    path('C', v.import_csv_itembm, name='import_csv_itembm'),
    path('rdoC/', v.import_csv_rdo, name='import_csv_rdo'),
    path('rdo/deleteitem/<int:id>/<int:ind>/', v.delete_item, name='delete_item'),
    path('rdo/<int:pk>/assinatura/', has_role_decorator('fiscal')(v.AssinaturaRDOView.as_view()), name='assinatura_rdo'),
    #Bm's
    path('bm/', has_role_decorator('bms')(v.BoletimList.as_view()), name='bm_list'),
    path('bm/<int:pk>/edit/', has_role_decorator('bms')(v.BoletimUpdate.as_view()), name='bm_update'),
    path('bm/create/', has_role_decorator('bms')(v.BoletimCreate.as_view()), name='bm_create'),
    path('bm/<int:pk>/', v.boletim_detail, name='bm_detail'),
    path('bm/<int:pk>/<int:id>/', v.bm_delete, name='bm_delete'),
    #Frs's
    path('frs/', manager_required(v.FrsList.as_view()), name='frs_list'),
    path('frs/<int:pk>/edit/', manager_required(v.FRSUpdate.as_view()), name='frs_update'),
    path('frs/create/', manager_required(v.FRSCreate.as_view()), name='frs_create'),
    path('frs/<int:pk>/', v.frs_detail, name='frs_detail'),
    path('frs/deleteitem/<int:pk>/<int:id>/', v.frsitem_delete, name='delete_itemfrs'),
    #cadastros
    path('aprovadordms/', v.aprovadordms_add, name='aprovadordms_add'),
    path('aprovadorbms/', v.aprovadorbms_add, name='aprovadorbms_add'),
    path('contrato/', v.contrato_add, name='contrato_add'),
    path('projeto_cod/', v.projeto_add, name='projeto_add'),
    path('area_rdo/', v.area_add, name='area_add'),
    path('solicitante_rdo/', v.solicitante_add, name='solicitante_add'),
    #exports/imports
    path('bmf/export/xlsx/', v.export_xlsx_func_bmf, name='export_xlsx_func_bmf'),
    path('bmf/exportmov/xlsx/', v.export_movimentacao, name='export_movimentacao'),
    path('bmf/exportmovall/xlsx/', v.export_movimentacao_completa, name='export_movimentacao_completa'),
    path('pdfbms/<int:pk>/', v.render_pdf_view, name='render_pdf_view'),
    path('rdo/deleteass/<int:pk>/<int:id>/', v.delete_assinatura, name='delete_assinatura'),
    path('export_csv/<int:pk>/', v.export_csv_view, name='export_csv'),
    #As's
    path('as/create/', has_role_decorator('as')(v.ASCreate.as_view()), name='as_create'),
    path('as/', has_role_decorator('as')(v.ASList.as_view()), name='as_list'),
    path('as/edit/<slug:slug>/', v.as_edit, name='as_edit'),
    path('as/<slug:slug>/', v.as_detail, name='as_detail'),
    path('as/deleteitem/<int:id>/<int:ind>/', v.delete_item_as, name='delete_item_as'),
############
 ]

material/views.py
import xlwt
import csv
import io
from django.urls import reverse
from datetime import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .models import Tratamento, TintaFundo, TintaIntermediaria, TintaAcabamento, Material
from .forms import MaterialForm, TratamentoForm, TintaFundoForm, TintaIntermediariaForm, TintaAcabamentoForm, MaterialForms
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
import os
from django.conf import settings
from usuarios.decorators import manager_required, superuser_required
from romaneio.models import Romaneio
from django.db.models import Sum
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from .utils import converter_afd_para_csv

@login_required
@manager_required
def tratamento_add(request):
    template_name = 'tratamento_add.html'
    tratamento_form = Tratamento()
    objects = Tratamento.objects.all()
    if request.method == 'POST' and request.POST.get('edit-form'):
        pk = request.POST.get('edit-form')
        tratamento = request.POST.get('main-tratamento')
        Tratamento.objects.filter(pk=pk).update(tratamento=tratamento)
        url = '#'
        return HttpResponseRedirect(url)
    elif request.method == 'POST':
        form=TratamentoForm(request.POST, instance=tratamento_form, prefix='main')
        if form.is_valid():
            form=form.save()
            url='#'
            return HttpResponseRedirect(url)
    else:
        form=TratamentoForm(instance=tratamento_form, prefix='main')
    context={'form':form,'objects_list': objects}
    return render(request, template_name, context)
@login_required
@manager_required
def tintafundo_add(request):
    template_name = 'tintafundo_add.html'
    tintaf_form = TintaFundo()
    objects = TintaFundo.objects.all()
    if request.method == 'POST' and request.POST.get('edit-form'):
        pk = request.POST.get('edit-form')
        tf = request.POST.get('main-tinta_fundo')
        TintaFundo.objects.filter(pk=pk).update(tinta_fundo=tf)
        url = '#'
        return HttpResponseRedirect(url)
    elif request.method == 'POST':
        form=TintaFundoForm(request.POST, instance=tintaf_form, prefix='main')
        if form.is_valid():
            form=form.save()
            url='#'
            return HttpResponseRedirect(url)
    else:
        form=TintaFundoForm(instance=tintaf_form, prefix='main')
    context={'form':form,'objects_list': objects}
    return render(request, template_name, context)
@login_required
@manager_required
def tintaintermediaria_add(request):
    template_name = 'tintaintermediaria_add.html'
    tintai_form = TintaIntermediaria()
    objects = TintaIntermediaria.objects.all()
    if request.method == 'POST' and request.POST.get('edit-form'):
        pk = request.POST.get('edit-form')
        ti = request.POST.get('main-tinta_intermediaria')
        TintaIntermediaria.objects.filter(pk=pk).update(tinta_intermediaria=ti)
        url = '#'
        return HttpResponseRedirect(url)
    elif request.method == 'POST':
        form=TintaIntermediariaForm(request.POST, instance=tintai_form, prefix='main')
        if form.is_valid():
            form=form.save()
            url='#'
            return HttpResponseRedirect(url)
    else:
        form=TintaIntermediariaForm(instance=tintai_form, prefix='main')
    context={'form':form,'objects_list': objects}
    return render(request, template_name, context)
@login_required
@manager_required
def tintaacabamento_add(request):
    template_name = 'tintaacabamento_add.html'
    tintaa_form = TintaAcabamento()
    objects = TintaAcabamento.objects.all()
    if request.method == 'POST' and request.POST.get('edit-form'):
        pk = request.POST.get('edit-form')
        ta = request.POST.get('main-tinta_acabamento')
        TintaAcabamento.objects.filter(pk=pk).update(tinta_acabamento=ta)
        url = '#'
        return HttpResponseRedirect(url)
    elif request.method == 'POST':
        form=TintaAcabamentoForm(request.POST, instance=tintaa_form, prefix='main')
        if form.is_valid():
            form=form.save()
            url='#'
            return HttpResponseRedirect(url)
    else:
        form=TintaAcabamentoForm(instance=tintaa_form, prefix='main')
    context={'form':form,'objects_list': objects}
    return render(request, template_name, context)


class MaterialList(ListView):
    model = Material
    template_name = 'material_list.html'
    paginate_by = 20
    context_object_name = 'objects_list'
    def get_queryset(self):
        queryset = super(MaterialList, self).get_queryset()
        search = self.request.GET.get('q')
        if search:
            queryset = queryset.filter(
                Q(n_romaneio__romaneio=search) |
                Q(concluido__icontains=search)
            )
        return queryset
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            vi = request.POST.get('valores')
            vi = str(vi)
            present = vi.split(",")
            present.pop()
            for i in present:
                if not i == "False":
                    Material.objects.filter(pk=i).update(concluido=True)
            url='#'
            return HttpResponseRedirect(url)

def material_detail(request, pk):
    template_name = 'material_detail.html'
    obj = Material.objects.get(pk=pk)
    link = f"https://monsertec.singularcode.net/material/{obj.pk}"
    context = {'object': obj, 'link':link}
    return render(request, template_name, context)

################### pdf view

def render_pdf_view(request, pk):
    obj = get_object_or_404(Material, pk=pk)
    template_path = 'qrcode.html'
    link = f"https://monsertec.singularcode.net/material/{obj.pk}"
    context = {'material': obj, 'link':link}
   
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')

    #if download
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

class MaterialCreate(CreateView):
    model = Material
    template_name = 'material_form.html'
    form_class = MaterialForm

class MaterialUpdate(UpdateView):
    model = Material
    template_name = 'material_form.html'
    form_class = MaterialForms

################## gráficos
def json_material(request,begin,end):
    data_inicial = begin
    data__final = end
    data = list(Material.objects.filter(n_romaneio__entrada__range=[data_inicial, data__final]).values('n_romaneio__area__area').annotate(Sum('m2')))
    return JsonResponse({'data':data})

def json_status(request,begin,end):
    data_inicial = begin
    data__final = end
    data = list(Material.objects.filter(n_romaneio__entrada__range=[data_inicial, data__final]).values('concluido').annotate(Sum('m2')))
    return JsonResponse({'data':data})

def json_ti(request):
    data = list(TintaIntermediaria.objects.values())
    return JsonResponse({'data':data})

def json_ta(request):
    data = list(TintaAcabamento.objects.values())
    return JsonResponse({'data':data})

def json_tratamento(request):
    data = list(Tratamento.objects.values())
    return JsonResponse({'data':data})

################### exportações
def export_xlsx(model, filename, queryset, columns):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="%s"' % filename

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet(model)

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    default_style = xlwt.XFStyle()

    rows = queryset
    for row, rowdata in enumerate(rows):
        row_num += 1
        for col, val in enumerate(rowdata):
            ws.write(row_num, col, val, default_style)

    wb.save(response)
    return response

@login_required
@manager_required
def export_xlsx_func_material(request):
    MDATA = datetime.now().strftime('%Y-%m-%d')
    model = 'Material'
    filename = 'material_exportados.xls'
    _filename = filename.split('.')
    filename_final = f'{_filename[0]}_{MDATA}.{_filename[1]}'
    queryset = Material.objects.all().values_list('pk','concluido','n_romaneio__area__area','n_romaneio__solicitante__solicitante', 'n_romaneio', 'jato__tratamento', 
    'tf__tinta_fundo','ti__tinta_intermediaria', 'ta__tinta_acabamento', 'cor', 'material', 'descricao',
     'polegada', 'm_quantidade', 'm2', 'raio', 'largura', 'altura', 'comprimento','lados','relatorio','n_romaneio__documento')

    columns = ('id','concluido','area','solicitante', 'Nº romaneio', 'Tratamento', 'Primer','TI', 
    'TA', 'cor', 'material', 'descricao', 'polegada', 'M / Quant.', 'm2', 'Raio', 'Largura', 'Altura', 
    'Comprimento/lados','QTD_Equip','Nº Relatório','Doc')
    response = export_xlsx(model, filename_final, queryset, columns)
    return response
def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        concluido = True if item.get('concluido') == 'True' else False
        n_romaneio = item.get('n_romaneio') # foreignkey
        jato = int(item.get('jato')) # foreignkey
        tf = int(item.get('tf')) # foreignkey
        ti = int(item.get('ti')) # foreignkey

material/templates/material_detail.html
{% extends "base.html" %}
{% load qr_code %}

{% block content %} 
<a href="{% url 'material:material_list'  %}">voltar</a>

    <h1> {{ object.material }}
        <td>
            {% if object.concluido %}
              <i class="fa fa-check-circle ok"></i>
            {% else %}
              <i class="fa fa-minus-circle no"></i>
            {% endif %}
        </td>
        <span class="pull-right">
            <a href="{% url 'material:material_edit' object.pk %}">
                <button type="button" class="btn btn-success">
                    <span class="fa fa-pencil"></span> Editar
                </button>
            </a>

        </span>
	</span>
        <span class="pull-right">
            <a href="{% url 'material:render_pdf_view' object.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="fa fa-pencil"></span> Imprimir
                </button>
            </a>
        </span>
    </h1>
<div class="row">
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Romaneio Nº:</th>
                    <td>
                        {{ object.n_romaneio }}
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Tratamento da superfície:</th>
                    <td>{{ object.jato }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tinta de Fundo (Primer):</th>
                    <td> {{ object.tf }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tinta Intermediária:</th>
                    <td>{{ object.ti }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tinta Acabamento:</th>
                    <td>{{ object.ta }}</td>
                </tr>
                <tr>
                    <th class="text-right">Cor:</th>
                    <td>{{ object.cor }}</td>
                </tr>
                <tr>
                    <th class="text-right">Tipo Material:</th>
                    <td>{{ object.material }}</td>
                </tr>
                <tr>
                    <th class="text-right">Descrição Material:</th>
                    <td>{{ object.descricao }}</td>
                </tr>
                <tr>
                    <th class="text-right">Polegada:</th>
                    <td>{{ object.polegada }}</td>
                </tr>
                <tr>
                    <th class="text-right">M linear / Quantidade:</th>
                    <td>{{ object.m_quantidade }}</td>
                </tr>
                <tr>
                    <th class="text-right">M²:</th>
                    <td>{{ object.m2 }}</td>
                </tr>
                <tr>
                    <th class="text-right">Raio:</th>
                    <td>{{ object.raio }}</td>
                </tr>
                <tr>
                    <th class="text-right">Largura:</th>
                    <td>{{ object.largura }}</td>
                </tr>
                <tr>
                    <th class="text-right">Altura:</th>
                    <td>{{ object.altura }}</td>
                </tr>
                <tr>
                    <th class="text-right">Comprimento/lados:</th>
                    <td>{{ object.comprimento }}</td>
                </tr>
                <tr>
                    <th class="text-right">QTD:</th>
                    <td>{{ object.lados }}</td>
                </tr>
                <tr>
                    <th class="text-right">Relatorio:</th>
                    <td><a href="/qualidade/{{ object.relatorio }}">RIP nº{{ object.relatorio }}</a></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-sm-6">
        <div class="d-flex justify-content-center " >
            {% qr_from_text link size="M" %}
        </div>
        <div class="d-flex justify-content-center " >
            <h5>QR CODE - IDPÇ </h5>
        </div>        
        
        
    </div>

</div>
{% endblock content %} 

material/templates/material_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %} 
<div class="row">
    <div class="col-sm-4">
        <form method="POST" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-control{% if field.errors %} has error {% endif %}" style="display: flex;justify-content: space-between;">
                <label for="{{ field.id_for_label }}">
                    {% if field.field.required %}
                        <span class="required">{{ field.label }} </span>
                        {% else %}
                        {{ field.label }}
                        {% endif %}
                </label>
                {% render_field field class="form-control-sm" %}
                {% for error in field.errors %}
                    <span class="text-muted">{{ error }}</span>
                {% endfor %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Cadastrar</button>
            
        </form>
    </div>
</div>

 {% endblock content %} 

material/templates/material_import.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input name="myfile" type="file" />
    <button type="submit" class="btn btn-success">Upload</button>
  </form>

{% endblock content %}

material/templates/material_list.html
{% extends "base.html" %}


{% block content %} 
    <div class="page-header">
        <h2><i class="fa fa-user"></i> Materiais
            <span class="pull-right">
                <div style="display: flex;">
                <a href="{% url 'material:material_add' %}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span>Adicionar
                    </button>
                </a>
                <a href="{% url 'material:export_xlsx_func_material' %}">
                    <button type="button" class="btn btn-info">
                        <span class="fa fa-plus"></span>Exportar Materiais
                    </button>
                </a>
                </div>
            </span>
        </h2>

        {% if objects_list %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nº Romaneio</th>
                    <th>TF</th>
                    <th>TI</th>
                    <th>TA</th>
                    <th>Tipo Mat.</th>
                    <th>M²</th>
                    <th>Descrição/Tag</th>
	            <th> RIP</th>
                    <th><i class="fa fa-check-circle"></i></th>
                </tr>
            </thead>
            <form method="POST" novalidate>
                {% csrf_token %}
            <tbody>
                {% for object in objects_list %}
                <tr>
                    <td>{{ object.n_romaneio }}</td>
                    <td>{{ object.tf }}</td>
                    <td>{{ object.ti }}</td>
                    <td>{{ object.ta}}</td>
                    <td><a href="{{ object.get_absolute_url }}">{{ object.material }}</a></td>
                    <td>{{ object.m2 }}</td>
                    <td>{{ object.descricao }}</td>
		    <td>{{ object.relatorio }}</td>
                    <td>{% if object.concluido %}
                        <i class="fa fa-check-circle ok"></i>
                      {% else %}
                        <label class="control control--checkbox">
                        <input type="checkbox" name="acceptRules" class="inline checkbox checkclass" id="checkbox-{{ object.pk }}" value="False"/>
                      </label></td>
                      {% endif %}
                </tr>
                 
                {% endfor %}
            </tbody>
        </table>
        <span class="pull-right">
            <div style="display: flex;">
           
                <button type="submit" class="btn btn-dark float-right">
                    <i class="fa fa-arrow-circle-o-up" aria-hidden="true"></i>
                </button>
           
            </div>
            <input hidden name="valores" id="valores">
        </span>
            </form> 
        {% else %}
        <p class="alert alert-warning">Sem Itens na Lista </p>
        {% endif %}
    </div>
    {% include "includes/pagination.html" %}

        
{% endblock content %} 
{% block js %}

<script>

    $(".checkclass").on('change', function() {
        if ($(this).is(':checked')) {
            valor = $(this).attr('id').replace('checkbox-','')
        $(this).attr('value', valor);
    }   else {
        $(this).attr('value', 'False');
    }
    });
    $(document).on('change', '.checkclass', function(){
            var txt = "";
            $('.checkclass').each(function(){
                txt += $(this).val()+"," ;
                txt = txt.replace('.','');
            });
            $('#valores').val(txt);
        });

</script>

{% endblock js %}

material/templates/qrcode.html
{% load qr_code %}
<head>
<style>
    @page {
        size: a7 portrait;
        margin: 1cm;
    }
</style>
</head>
{% load qr_code %}
<body>
    <img src="media/logo.png" alt="blah">
    <div >
        <th>{{ material.material }} - </th>
        <legend>Romaneio nº{{ material.n_romaneio }}</legend>
    </div>
    <div >
        {% qr_from_text link image_format="png" %}
    </div>
</body>

material/templates/tintaacabamento_add.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block content %} 

<div class="row">
    <div class="col-sm-12">
        <form method="POST" novalidate>
            {% csrf_token %}
            <legend style="border-bottom: 1px solid #e5e5e5;">Tinta Acabamento</legend>
            <div class="row">
                <div class="col-sm-6">
                    {% for field in form.visible_fields %}
                    <div class="form-group{% if field.errors %} has error {% endif %}">
                        <label for="{{ field.id_for_label }}">
                            {% if field.field.required %}
                                <span class="required">{{ field.label }} </span>
                                {% else %}
                                {{ field.label }}
                                {% endif %}
                        </label>
                        {% render_field field class="form-control" %}
                        {% for error in field.errors %}
                            <span class="text-muted">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <div class="form-row">
                <div class="form-group col-md-1">
                    <input placeholder="ID"class="form-control"name="edit-form" id="edit-form"type="text">
                </div>
                <div class="form-group col-md-1">
                <button class="btn btn-primary" value="Save">
                   Salvar
                </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row" style="margin-top: 20px;">
    {% if objects_list %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                {% for object in objects_list %}
                <tr>
                    <td>{{ object.pk }}</td>
                    <td>{{ object.tinta_acabamento}}</td>
                </tr>
                 
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="alert alert-warning">Sem Itens na Lista </p>
        {% endif %}
</div>

{% endblock content %} 

material/templates/tintafundo_add.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block content %} 

<div class="row">
    <div class="col-sm-12">
        <form method="POST" novalidate>
            {% csrf_token %}
            <legend style="border-bottom: 1px solid #e5e5e5;">Tinta de Fundo</legend>
            <div class="row">
                <div class="col-sm-6">
                    {% for field in form.visible_fields %}
                    <div class="form-group{% if field.errors %} has error {% endif %}">
                        <label for="{{ field.id_for_label }}">
                            {% if field.field.required %}
                                <span class="required">{{ field.label }} </span>
                                {% else %}
                                {{ field.label }}
                                {% endif %}
                        </label>
                        {% render_field field class="form-control" %}
                        {% for error in field.errors %}
                            <span class="text-muted">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <div class="form-row">
                <div class="form-group col-md-1">
                    <input placeholder="ID"class="form-control"name="edit-form" id="edit-form"type="text">
                </div>
                <div class="form-group col-md-1">
                <button class="btn btn-primary" value="Save">
                   Salvar
                </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row" style="margin-top: 20px;">
    {% if objects_list %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                {% for object in objects_list %}
                <tr>
                    <td>{{ object.pk }}</td>
                    <td>{{ object.tinta_fundo}}</td>
                </tr>
                 
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="alert alert-warning">Sem Itens na Lista </p>
        {% endif %}
</div>

{% endblock content %} 

material/templates/upload.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load bootstrap %}

{% block content %} 
    <h2>Upload de Arquivos de ponto</h2>
    <form action="{% url 'material:processar_arquivos' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="arquivos">Selecione os arquivos AFD:</label>
        <input type="file" name="arquivos" id="arquivos" accept=".txt" multiple required>
        <br>
        <input type="submit" value="Processar e Baixar">
    </form>
{% endblock content %} 